name: pyo_oracle
channels:
  - conda-forge
dependencies:
  - python>=3.9
  - erddapy
  - pandas>=2.0
  - httpx
  - xarray
  - netCDF4
  - matplotlib-base
  - cartopy
  - cmocean
  - seaborn
  - ipython
  - pytest
  - pytest-cov
  - respx
  - flake8
  - ruff
  - pip
  - pip:
      - mkdocs-material
      - "mkdocstrings[python]"
      - mkdocs-jupyter
